-- Intermediate SQL — Problems 31–40 

INSERT INTO order_items
(order_item_id, order_id, product_id, quantity, unit_price)
VALUES
(1, 1, 1, 1, 85000.00),
(2, 1, 2, 1, 1200.00),
(3, 2, 4, 1, 55000.00),
(4, 2, 2, 2, 1200.00),
(5, 3, 3, 1, 4500.00),
(6, 3, 5, 1, 2500.00),
(7, 4, 6, 1, 22000.00),
(8, 5, 7, 1, 15000.00),
(9, 5, 8, 2, 3000.00),
(10, 6, 7, 1, 15000.00);

CREATE TABLE order_items (
    order_item_id INT PRIMARY KEY,
    order_id INT,
    product_id INT,
    quantity INT,
    unit_price DECIMAL(12,2),
 
    FOREIGN KEY (order_id)
        REFERENCES orders(order_id),
 
    FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);

-- P31 Display customer names along with their order IDs and order amounts. 
select c.customer_name, o.order_id, o.total_amount
from customers c
join orders o
on c.customer_id = o.customer_id; 

-- P32 Show employee name, department name, and salary.
select e.first_name, e.salary, d.department_name
from employees e
join departments d
on e.department_id = d.department_id;

-- P33 Find customers whose order status is delivered
select c.customer_name
from customers c
left join orders e
on c.customer_id = e.customer_id
where e.status = 'delivered';

-- P34 Show order ID, customer name, order date, and status.
select o.order_id, c.customer_name, o.order_date, o.status
from customers c
join orders o
on c.customer_id = o.customer_id;

-- P35 Find products that have never appeared in order_items.
select p.product_name
from products p
left join order_items o
on o.product_id = p.product_id
where o.product_id is null;

-- P36 Calculate total order value for every customer.
select c.customer_name, sum(o.total_amount)
from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_name;

-- P37 Find customers whose total order value exceeds 10,000.
select c.customer_name, sum(o.total_amount) as total
from customers c
join orders o 
on c.customer_id = o.customer_id
group by c.customer_name
having total > 10000;

-- P38 Find the average order amount for each customer.
select c.customer_name, avg(o.total_amount)
from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_name;

-- P39 Calculate revenue generated by each product using order_items.
select product_id, sum(unit_price * quantity) as revenue 
from order_items
group by product_id;

-- P40 Find the five products with the highest total quantity sold.
select p.product_name, sum(o.quantity) as total
from products p
join order_items o
on p.product_id = o.product_id
group by p.product_id
order by total desc
limit 5;
  



select * from departments;
select * from employees;
select * from products;
select * from customers;
select * from orders;
select * from order_items;
