-- Intermediate SQL — Problems 31–40 

-- P31 Display customer names along with their order IDs and order amounts. 
select c.customer_name, o.order_id, o.total_amount
from customers c
join orders o
on c.customer_id = o.customer_id; 

-- P32 Show employee name, department name, and salary.
select e.first_name, e.salary, d.department_name
from employees e
join departments d
on e.department_id = d.department_id;

-- P33 Find customers whose order status is delivered
select c.customer_name
from customers c
left join orders e
on c.customer_id = e.customer_id
where e.status = 'delivered';

-- P34 Show order ID, customer name, order date, and status.
select o.order_id, c.customer_name, o.order_date, o.status
from customers c
join orders o
on c.customer_id = o.customer_id;

-- P35 Find products that have never appeared in order_items.

-- P36 Calculate total order value for every customer.
select c.customer_name, sum(o.total_amount)
from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_name;

-- P37 Find customers whose total order value exceeds 10,000.
select c.customer_name, sum(o.total_amount) as total
from customers c
join orders o 
on c.customer_id = o.customer_id
group by c.customer_name
having total > 10000;

-- P38 Find the average order amount for each customer.
select c.customer_name, avg(o.total_amount)
from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_name;

-- P39 Calculate revenue generated by each product using order_items.